server.port=8081

spring.datasource.url=jdbc:h2:file:./data/mecatronicadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=mecatronica
spring.datasource.password=mecatronica2024
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
